// Package main provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version (devel) DO NOT EDIT.
package main

// ComposedMessage defines model for ComposedMessage.
type ComposedMessage struct {
	Body      *string     `json:"body,omitempty"`
	Recipient interface{} `json:"recipient"`
	Sender    string      `json:"sender"`
	Subject   string      `json:"subject"`
}

// GroupCreation defines model for GroupCreation.
type GroupCreation struct {
	Groupname string   `json:"groupname"`
	Usernames []string `json:"usernames"`
}

// A message recipient representing a group of users
type GroupRecipient struct {
	Groupname *string `json:"groupname,omitempty"`
}

// Message defines model for Message.
type Message struct {
	Body      *string     `json:"body,omitempty"`
	Id        float32     `json:"id"`
	Re        *float32    `json:"re,omitempty"`
	Recipient interface{} `json:"recipient"`
	Sender    string      `json:"sender"`
	SentAt    string      `json:"sentAt"`
	Subject   string      `json:"subject"`
}

// ReplyMessage defines model for ReplyMessage.
type ReplyMessage struct {
	Body    *string `json:"body,omitempty"`
	Sender  string  `json:"sender"`
	Subject string  `json:"subject"`
}

// A message recipient representing a single user
type UserRecipient struct {
	Username *string `json:"username,omitempty"`
}

// UserRegistration defines model for UserRegistration.
type UserRegistration struct {
	Username string `json:"username"`
}

// PostGroupsJSONBody defines parameters for PostGroups.
type PostGroupsJSONBody GroupCreation

// PostMessagesJSONBody defines parameters for PostMessages.
type PostMessagesJSONBody ComposedMessage

// PostMessagesIdRepliesJSONBody defines parameters for PostMessagesIdReplies.
type PostMessagesIdRepliesJSONBody ReplyMessage

// PostUsersJSONBody defines parameters for PostUsers.
type PostUsersJSONBody UserRegistration

// PostGroupsJSONRequestBody defines body for PostGroups for application/json ContentType.
type PostGroupsJSONRequestBody PostGroupsJSONBody

// PostMessagesJSONRequestBody defines body for PostMessages for application/json ContentType.
type PostMessagesJSONRequestBody PostMessagesJSONBody

// PostMessagesIdRepliesJSONRequestBody defines body for PostMessagesIdReplies for application/json ContentType.
type PostMessagesIdRepliesJSONRequestBody PostMessagesIdRepliesJSONBody

// PostUsersJSONRequestBody defines body for PostUsers for application/json ContentType.
type PostUsersJSONRequestBody PostUsersJSONBody
